maintenance toggle
appgate/sdpctl pull request #281
Opened 2022-09-08 07:54 UTC by danijeel

New command: Toggle maintenance mode on a single controller.

![image](https://user-images.githubusercontent.com/1218385/189066932-64ae0cd0-5dc9-40ed-b2fc-85a8468e794a.png)

2022-09-08 07:55 UTC, danijeel commented
I'd like to get some input on the docs and wording here...

2022-09-08 08:32 UTC, thomascellerier commented
Regarding wording:

I would use "disable maintenance mode" rather than "set maintenance mode to false".
Same for "enable maintenance mode" rather than "set maintenance mode to true".

On the description: "An appliance in maintenance mode won't allow to perform POST, PUT, PATCH or DELETE methods.
This is a superuser function and should only be used if you know what you are doing."

Right now maintenance mode is only applicable to Controllers though the API currently let's you set it on any appliance (something to fix?).
Maintenance mode behaves differently in 5.5 and 6.0. In 6.0 clients are still able to connect.

So maybe something like:

A Controller in maintenance mode will not accept any API calls besides disabling maintenance mode. Starting in version 6.0, clients will still function as usual while a Controller is in  maintenance mode.
This is a superuser function and should only be used if you know what you are doing.

The version dependent information might be logged depending on API version?

2022-09-08 09:28 UTC, kajes requested changes
Is the toggle command really necessary if we have enable and disable commands? I find it a bit superfluous and confusing.

2022-09-08 09:28 UTC, kajes commented on pkg/docs/maintenance.go
> +    This function is a advance function, and should be used with care,
```suggestion
    For advanced users only.
```

2022-09-08 09:53 UTC, thomascellerier commented
Its fine by me to remove the toggle sub-command, you would generally either want to explicitly enable or disable and having separate sub commands for that makes mistakes harder.

2022-09-09 12:21 UTC, thomascellerier approved these changes
Tried it out looks good.

2022-09-12 07:33 UTC, kajes approved these changes

2022-09-12 14:59 UTC, merged