Fixed typos
appgate/sdpctl pull request #372
Opened 2023-01-27 20:26 UTC by aaronpalermo

Replaced 'mange' with 'manage' in several files.

2023-01-27 20:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/appgate/sdpctl?pullRequest=372) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/appgate/sdpctl?pullRequest=372) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: Aaron Palermo<br/>:x: aaronpalermo<br/><hr/>**Aaron Palermo** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/appgate/sdpctl?pullRequest=372) it.</sub>

2023-01-30 08:02 UTC, thomascellerier commented
Looks good, you need to sign the CLA first before we can merge.

2023-01-30 10:10 UTC, kajes requested changes
Don't merge this now. The html-files are generated, so the typos should be fixed in the source.

2023-01-30 10:17 UTC, kajes approved these changes
Ok, just did an extra check, and this seems to change just the things that would be generated anyway, so good to merge :+1: .

2023-01-30 10:18 UTC, merged